export const content = {
  helpArmy: {
    pageMainContent: {
      id: 'helpArmy01',
      title: 'Українські військові потребують:',
      requirements: [
        'Сучасні електронні засоби для нічного спостереження і водіння авто',
        'Літальні апарати для аеророзвідки і корегуванню вогню',
        'Автівки і ремонт пошкоджених в бою транспортних засобів',
        'Потужні засоби зв’язку і супутникові телефони',
        'Тактична медицина',
        'Амуніція, засоби захисту',
      ],
    },
  },
  helpChildren: {
    pageMainContent: {
      id: 'helpChildren01',
      title: 'Lorem ipsum dolor sit amet:',
      requirements: [
        'Lorem ipsum dolor sit amet',
        'Lorem ipsum dolor sit amet',
        'Lorem ipsum dolor sit amet',
        'Lorem ipsum dolor sit amet',
        'Lorem ipsum dolor sit amet',
        'Lorem ipsum dolor sit amet',
        'Lorem ipsum dolor sit amet',
        'Lorem ipsum dolor sit amet',
      ],
    },
    gallery: [
      {
        id: 'helpChildrenGallery01',
        name: 'Никіфоров Павло Романович',
        dates: '12.12.1983 - 20.03.2022',
        position: 'Командир роти',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin quis finibus ante, id laoreet mi. Nullam vestibulum imperdiet tellus vitae tincidunt. Fusce metus risus.',
      },
      {
        id: 'helpChildrenGallery02',
        name: 'Любомирський Петро Венедиктович',
        dates: '15.05.1991 - 14.04.2022',
        position: 'Командир взводу розвідки',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin quis finibus ante, id laoreet mi. Nullam vestibulum imperdiet tellus vitae tincidunt. Fusce metus risus.',
      },
      {
        id: 'helpChildrenGallery03',
        name: "прізвище ім'я по батькові",
        dates: '00.00.0000 - 00.00.0000',
        position: 'Посада у Батальйоні',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin quis finibus ante, id laoreet mi. Nullam vestibulum imperdiet tellus vitae tincidunt. Fusce metus risus.',
      },
      {
        id: 'helpChildrenGallery04',
        name: "прізвище ім'я по батькові",
        dates: '00.00.0000 - 00.00.0000',
        position: 'Посада у Батальйоні',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin quis finibus ante, id laoreet mi. Nullam vestibulum imperdiet tellus vitae tincidunt. Fusce metus risus.',
      },
      {
        id: 'helpChildrenGallery05',
        name: "прізвище ім'я по батькові",
        dates: '00.00.0000 - 00.00.0000',
        position: 'Посада у Батальйоні',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin quis finibus ante, id laoreet mi. Nullam vestibulum imperdiet tellus vitae tincidunt. Fusce metus risus.',
      },
      {
        id: 'helpChildrenGallery06',
        name: "прізвище ім'я по батькові",
        dates: '00.00.0000 - 00.00.0000',
        position: 'Посада у Батальйоні',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin quis finibus ante, id laoreet mi. Nullam vestibulum imperdiet tellus vitae tincidunt. Fusce metus risus.',
      },
    ],
  },
  aero: {
    pageMainContent: {
      id: 'aero01',
      title: 'Lorem ipsum dolor sit amet:',
      requirements: [
        'Lorem ipsum dolor sit amet',
        'Lorem ipsum dolor sit amet',
        'Lorem ipsum dolor sit amet',
        'Lorem ipsum dolor sit amet',
        'Lorem ipsum dolor sit amet',
        'Lorem ipsum dolor sit amet',
        'Lorem ipsum dolor sit amet',
        'Lorem ipsum dolor sit amet',
      ],
    },
  },
  about: {
    gallery: [
      {
        id: 'aboutGallery01',
        name: 'Тарас тополя',
        position: 'Засновник',
        text: 'Фронтмен гурту Антитіла, спікер Молодіжної Ради при Президенті України, молодіжний Посол UNICEF в Україні (2019-2022), стрілець-парамедик 130 батальйону ТРО.',
      },
      {
        subtitle: 'Наглядова рада',
      },
      {
        id: 'aboutGallery02',
        name: 'СЕРГІЙ ВУСИК',
        position: 'Голова наглядової ради',
        text: 'Директор, співзасновник гурту Антитіла, музикант, режисер, член наглядових рад ГО ВАМП та ГО УААСП, стрілець-парамедик 130 батальйону ТРО.',
      },
      {
        id: 'aboutGallery03',
        name: 'Дмитро Нужний',
        text: 'Звукорежисер гурту Антитіла, водій-стрілець добровольчого формування «Загін територіальної самооборони «Березняки», в/ч А7040, волонтер.',
      },
      {
        id: 'aboutGallery04',
        name: 'Денис Федюнін',
        text: 'Координатор проектів ІПО, водій-стрілець добровольчого формування «Загін територіальної самооборони «Березняки», в/ч А7040, волонтер.',
      },
      {
        id: 'aboutGallery05',
        name: 'Дмитро Водовозов',
        text: 'Музикант гурту Антитіла, водій-стрілець добровольчого формування «Загін територіальної самооборони «Березняки», в/ч А7040, волонтер.',
      },
      {
        id: 'aboutGallery06',
        name: 'Михайло Чирко',
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin quis finibus ante, id laoreet mi, волонтер.',
      },
      {
        id: 'aboutGallery07',
        name: 'Катерина Нечаєва',
        text: 'Керівник БФ “Вільні UA” з 2014 року, підприємець, волонтер.',
      },
      {
        subtitle: 'Директор фонду',
      },
      {
        id: 'aboutGallery08',
        name: 'Родіон',
        text: 'example@gmail.com',
      },
    ],
  },
  news: {
    gallery: 'toBeGenerated',
    contentSource: 'title',
  },
  reports: {
    photos: 'toBeGenerated',
    gallery: {
      report1: [
        { id: 'report1-1' },
        { id: 'report1-2' },
        { id: 'report1-3' },
        { id: 'report1-4' },
        { id: 'report1-5' },
        { id: 'report1-6' },
        { id: 'report1-7' },
        { id: 'report1-8' },
        { id: 'report1-9' },
        { id: 'report1-10' },
      ],
      report2: [
        { id: 'report2-1' },
        { id: 'report2-2' },
        { id: 'report2-3' },
        { id: 'report2-4' },
        { id: 'report2-5' },
        { id: 'report2-6' },
        { id: 'report2-7' },
        { id: 'report2-8' },
        { id: 'report2-9' },
        { id: 'report2-10' },
      ],
      report3: [
        { id: 'report3-1' },
        { id: 'report3-2' },
        { id: 'report3-3' },
        { id: 'report3-4' },
        { id: 'report3-5' },
        { id: 'report3-6' },
        { id: 'report3-7' },
        { id: 'report3-8' },
        { id: 'report3-9' },
        { id: 'report3-10' },
      ],
      report4: [
        { id: 'report4-1' },
        { id: 'report4-2' },
        { id: 'report4-3' },
        { id: 'report4-4' },
        { id: 'report4-5' },
        { id: 'report4-6' },
        { id: 'report4-7' },
        { id: 'report4-8' },
        { id: 'report4-9' },
        { id: 'report4-10' },
      ],
      report5: [
        { id: 'report5-1' },
        { id: 'report5-2' },
        { id: 'report5-3' },
        { id: 'report5-4' },
        { id: 'report5-5' },
        { id: 'report5-6' },
        { id: 'report5-7' },
        { id: 'report5-8' },
        { id: 'report5-9' },
        { id: 'report5-10' },
      ],
      report6: [
        { id: 'report6-1' },
        { id: 'report6-2' },
        { id: 'report6-3' },
        { id: 'report6-4' },
        { id: 'report6-5' },
        { id: 'report6-6' },
        { id: 'report6-7' },
        { id: 'report6-8' },
        { id: 'report6-9' },
        { id: 'report6-10' },
      ],
      report7: [
        { id: 'report7-1' },
        { id: 'report7-2' },
        { id: 'report7-3' },
        { id: 'report7-4' },
        { id: 'report7-5' },
        { id: 'report7-6' },
        { id: 'report7-7' },
        { id: 'report7-8' },
        { id: 'report7-9' },
        { id: 'report7-10' },
      ],
      report8: [
        { id: 'report8-1' },
        { id: 'report8-2' },
        { id: 'report8-3' },
        { id: 'report8-4' },
        { id: 'report8-5' },
        { id: 'report8-6' },
        { id: 'report8-7' },
        { id: 'report8-8' },
        { id: 'report8-9' },
        { id: 'report8-10' },
      ],
      report9: [
        { id: 'report9-1' },
        { id: 'report9-2' },
        { id: 'report9-3' },
        { id: 'report9-4' },
        { id: 'report9-5' },
        { id: 'report9-6' },
        { id: 'report9-7' },
        { id: 'report9-8' },
        { id: 'report9-9' },
        { id: 'report9-10' },
      ],
    },
  },
};